"""initial schema

Revision ID: b376b1e97852
Revises: 
Create Date: 2026-09-04 16:30:08.014526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b376b1e97852'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialog_states',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('fszet_encrypted', sa.Text(), nullable=True),
    sa.Column('access_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_uid', sa.String(length=64), nullable=True),
    sa.Column('student_uid', sa.String(length=64), nullable=True),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.Column('group_uids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('feed_token', sa.String(length=64), nullable=False),
    sa.Column('morning_digest_at', sa.String(length=5), nullable=True),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('notify_on_change', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_feed_token'), ['feed_token'], unique=True)

    op.create_table('lesson_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_uid', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_uid', name='uq_revision_user_lesson')
    )
    with op.batch_alter_table('lesson_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_revisions_lesson_uid'), ['lesson_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_revisions_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('lessons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_snapshot_user_day')
    )
    with op.batch_alter_table('schedule_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_snapshots_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_snapshots_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_snapshots_day'))

    op.drop_table('schedule_snapshots')
    with op.batch_alter_table('lesson_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_revisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_revisions_lesson_uid'))

    op.drop_table('lesson_revisions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_feed_token'))

    op.drop_table('users')
    op.drop_table('dialog_states')
    # ### end Alembic commands ###
